# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_updatecrime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=50)),
                ('carbrand', models.CharField(max_length=60)),
                ('Ownername', models.CharField(max_length=60)),
                ('Licence', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Age', models.CharField(max_length=20)),
                ('Temp_Address', models.CharField(max_length=20)),
                ('Pan', models.CharField(max_length=20)),
                ('Vehicle_name', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('Vehicle_is', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=20)),
                ('YOM', models.CharField(max_length=20)),
                ('Engine_NO', models.CharField(max_length=20)),
                ('Seating_Cap', models.CharField(max_length=20)),
            ],
        ),
    ]
