# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_allvehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allvehicle',
            old_name='Vehicle_name',
            new_name='Fuel',
        ),
        migrations.AddField(
            model_name='allvehicle',
            name='vname',
            field=models.CharField(default=11.59, max_length=60),
            preserve_default=False,
        ),
    ]
