# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('emp_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='None', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(help_text='Minimum of 8 Characters', max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
